apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "aureoncare.fullname" . }}-uploads
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aureoncare.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - {{ .Values.uploads.persistence.accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.uploads.persistence.size | default "10Gi" }}
  {{- if .Values.uploads.persistence.storageClass }}
  storageClassName: {{ .Values.uploads.persistence.storageClass }}
  {{- end }}
